spring:
  datasource:
    #配置基本数据源
    url: jdbc:mysql://127.0.0.1:3306/gathering-dreams?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    password: a1160124552
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #配置其他数据源
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvicionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    #采用lettuce连接池
  lettuce:
    pool:
      max-active: 10
      max-idle: 10
      min-idle: 1
      time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null #Json处理时忽略非空字段

  redis:
    port: 6380
    host: 192.168.48.129

