server:
  port: 80
spring:
  profiles:
    group:
      "default": dfDB,dfDefaultAddress,dfNetty
    active: default
  application:
    name: gathering-dreams
logging:
  group:
    entity: com.hzh.gatheringproject.controller,com.hzh.gatheringproject.service,com.hzh.gatheringproject.mapper
    common: com.hzh.gatheringproject
  level:
    root: info
    entity: warn
    common: info
  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 100KB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log

task:
  pool:
    corePoolSize: 5
    maxPoolSize: 20
    keepAliveSeconds: 300
    queueCapacity: 50
